name: Kapacity master branch release

on:
  push:
    branches:
      - master
    paths-ignore:
      - version.properties

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        env:
          GIT_AUTHOR_NAME: "Github Action"
          GIT_COMMITTER_NAME: "Github Action"
          GIT_AUTHOR_EMAIL: "action@github.com"
          GIT_COMMITTER_EMAIL: "action@github.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PRIV_KEY: ${{ secrets.GPG_PRIV_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "$GPG_PRIV_KEY" > secring.text
          gpg --allow-secret-key-import --import --batch secring.text
          echo "nexusUsername=$OSSRH_USERNAME" >> gradle.properties
          echo "nexusPassword=$OSSRH_PASSWORD" >> gradle.properties
          echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties
          echo "signing.password=$SIGNING_PASSWORD" >> gradle.properties
          ./gradlew clean test release --no-daemon